-- Script para poblar la tabla cuentas_auxiliares con los datos del CSV
-- Ejecutar después de aplicar las migraciones 58b9d320b914 y 77b1106498dc

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at) VALUES
(gen_random_uuid(), '14050101', 'MATERIAS PRIMAS', true, NOW(), NOW()),
(gen_random_uuid(), '14050501', 'MATERIAS PRIMAS', true, NOW(), NOW()),
(gen_random_uuid(), '14100505', 'PRODUCTO EN PROCESO MP', true, NOW(), NOW()),
(gen_random_uuid(), '14100510', 'PRODUCTO EN PROCESO MOD', true, NOW(), NOW()),
(gen_random_uuid(), '14100515', 'PRODUCTO EN PROCESO CIF', true, NOW(), NOW()),
(gen_random_uuid(), '14101005', 'PROD. EN PROC ORDENES ABIERTA MP', true, NOW(), NOW()),
(gen_random_uuid(), '14101010', 'PROD. EN PROC ORDENES ABIERTA MOD', true, NOW(), NOW()),
(gen_random_uuid(), '14101015', 'PROD. EN PROC ORDENES ABIERTA CIF', true, NOW(), NOW()),
(gen_random_uuid(), '14280501', 'PLATANO', true, NOW(), NOW()),
(gen_random_uuid(), '14280502', 'PLANTACIONES DE CAFE', true, NOW(), NOW()),
(gen_random_uuid(), '14301001', 'PRODUCTOS TERMINADOS MP', true, NOW(), NOW()),
(gen_random_uuid(), '14301002', 'PRODUCTOS TERMINADOS MOD', true, NOW(), NOW()),
(gen_random_uuid(), '14301003', 'PRODUCTOS TERMINADOS CIF', true, NOW(), NOW()),
(gen_random_uuid(), '14301004', 'INVENTARIO PRODUCTO DEFECTUOSO', true, NOW(), NOW()),
(gen_random_uuid(), '14350101', 'MERCANCIA NO FABRICADA POR LA EMPRESA', true, NOW(), NOW()),
(gen_random_uuid(), '14350102', 'IMPUESTO AL CONSUMO', true, NOW(), NOW()),
(gen_random_uuid(), '14350103', 'BONOS', true, NOW(), NOW()),
(gen_random_uuid(), '14350104', 'UTENSILIOS MUEBLES-ENSERES Y REPUESTOS', true, NOW(), NOW()),
(gen_random_uuid(), '14350105', 'IMPUESTO IBUA BEBIDAS', true, NOW(), NOW()),
(gen_random_uuid(), '14550101', 'DOTACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '14600101', 'EMPAQUES Y EMBALAJES', true, NOW(), NOW()),
(gen_random_uuid(), '14659001', 'MERCANCIA EN TRANSITO', true, NOW(), NOW()),
(gen_random_uuid(), '14990501', 'PUENTE SALDOS INICIALES', true, NOW(), NOW()),
(gen_random_uuid(), '15040501', 'URBANOS', true, NOW(), NOW()),
(gen_random_uuid(), '15041001', 'RURALES', true, NOW(), NOW()),
(gen_random_uuid(), '15080501', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15080502', 'CONSTRUCCIONES Y EDIFICACIONES FABRICA', true, NOW(), NOW()),
(gen_random_uuid(), '151201001', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15120501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15160501', 'LOCALES', true, NOW(), NOW()),
(gen_random_uuid(), '15160597', 'REVALORIZACION LOCALES', true, NOW(), NOW()),
(gen_random_uuid(), '15160598', 'DETERIORO LOCALES', true, NOW(), NOW()),
(gen_random_uuid(), '15162001', 'FABRICAS Y PLANTAS INDUSTRIALES', true, NOW(), NOW()),
(gen_random_uuid(), '15162097', 'REVALORIZACION FABRICA', true, NOW(), NOW()),
(gen_random_uuid(), '15162098', 'DETERIORO FABRICA', true, NOW(), NOW()),
(gen_random_uuid(), '15200102', 'MAQUINARIA Y EQUIPO EN COMODATO', true, NOW(), NOW()),
(gen_random_uuid(), '15200103', 'MAQUINARIA Y EQUIPO ADQUIRIDA EN LEASING', true, NOW(), NOW()),
(gen_random_uuid(), '15200197', 'REVALORIZACION MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15200198', 'DETERIORO MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15200199', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
(gen_random_uuid(), '15280501', 'EQUIPO DE PROCESAMIENTO DE DATOS', true, NOW(), NOW()),
(gen_random_uuid(), '15280597', 'REVALORIZACION  EQUIP PROCES. DATOS', true, NOW(), NOW()),
(gen_random_uuid(), '15280598', 'DETERIORO EQUIP PROCES. DATOS', true, NOW(), NOW()),
(gen_random_uuid(), '15280599', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
(gen_random_uuid(), '15281001', 'EQUIPO DE TELECOMUNICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15281097', 'REVALORIZACION EQUIP TELECOMUNICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15281098', 'DETERIORO EQUIP TELECOMUNICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15281099', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
(gen_random_uuid(), '15400501', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
(gen_random_uuid(), '15400597', 'REVALORIZACION FLOTA Y EQUIPO DE TRANSP.', true, NOW(), NOW()),
(gen_random_uuid(), '15400598', 'DETERIORO FLOTA Y EQUIPO DE TRANSP.', true, NOW(), NOW()),
(gen_random_uuid(), '15400599', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
(gen_random_uuid(), '15640501', 'CULTIVOS EN DESARROLLO', true, NOW(), NOW()),
(gen_random_uuid(), '15640502', 'CULTIVOS EN DESARROLLO - INSUMOS', true, NOW(), NOW()),
(gen_random_uuid(), '15640503', 'CULTIVOS EN DESARROLLO-COMPRA HERRAMIEN.', true, NOW(), NOW()),
(gen_random_uuid(), '15640504', 'CULTIVOS EN DESARROLLO - TRABAJADORES', true, NOW(), NOW()),
(gen_random_uuid(), '156499', 'CULTIVOS EN DESARROLLO - OTROS', true, NOW(), NOW()),
(gen_random_uuid(), '15880501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15881001', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
(gen_random_uuid(), '15881501', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
(gen_random_uuid(), '15881501-1', 'EQUIPO COMPUTACION YCOMUNICACION SIN IVA', true, NOW(), NOW()),
(gen_random_uuid(), '15883001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
(gen_random_uuid(), '15887001', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15920501', 'CONSTRUCCIONES Y  EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15921001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15921501', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
(gen_random_uuid(), '15922001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
(gen_random_uuid(), '15923501', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
(gen_random_uuid(), '15990801', 'URBANOS', true, NOW(), NOW()),
(gen_random_uuid(), '15991601', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '15992001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '15992801', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
(gen_random_uuid(), '15994001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
(gen_random_uuid(), '16350101', 'LICENCIA INVIMA', true, NOW(), NOW()),
(gen_random_uuid(), '16350201', 'LICENCIA SIESA', true, NOW(), NOW()),
(gen_random_uuid(), '17052001', 'SEGUROS Y FIANZAS', true, NOW(), NOW()),
(gen_random_uuid(), '17059501', 'GASTOS PAGADOS POR ANTICIPADO', true, NOW(), NOW()),
(gen_random_uuid(), '17100801', 'MEJORA A PROPIEDAD AJENA T. NUEVAS', true, NOW(), NOW()),
(gen_random_uuid(), '17102801', 'CONSTRIBUCIONES Y AFILIACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '17103201', 'CAPACITACION DE PERSONAL', true, NOW(), NOW()),
(gen_random_uuid(), '17104001', 'LICENCIAS', true, NOW(), NOW()),
(gen_random_uuid(), '17104401', 'PUBLICIDAD, PROPAGANDA Y PROMOCION', true, NOW(), NOW()),
(gen_random_uuid(), '17106001', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
(gen_random_uuid(), '17109501', 'OTROS', true, NOW(), NOW()),
(gen_random_uuid(), '17109502', 'CANON VARIABLE - LOCALES', true, NOW(), NOW()),
(gen_random_uuid(), '17109503', 'ENERGIA', true, NOW(), NOW()),
(gen_random_uuid(), '18959501', 'IVA RETENIDO EN VENTAS', true, NOW(), NOW()),
(gen_random_uuid(), '19100801', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
(gen_random_uuid(), '19101201', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
(gen_random_uuid(), '19101601', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
(gen_random_uuid(), '19102001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
(gen_random_uuid(), '19103201', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
(gen_random_uuid(), '23300101', 'ORDENES DE COMPRA POR UTILIZAR', true, NOW(), NOW()),
(gen_random_uuid(), '23351501', 'LIBROS, SUSCRIP, PERIODICOS Y REVISTAS', true, NOW(), NOW()),
(gen_random_uuid(), '23352001', 'COMISIONES', true, NOW(), NOW()),
(gen_random_uuid(), '23352501', 'HONORARIOS', true, NOW(), NOW()),
(gen_random_uuid(), '23353001', 'SERVICIOS TECNICOS', true, NOW(), NOW()),
(gen_random_uuid(), '23353501', 'SERVICIOS DE MANTENIMIENTO', true, NOW(), NOW()),
(gen_random_uuid(), '23354001', 'ARRENDAMIENTO', true, NOW(), NOW()),
(gen_random_uuid(), '23354501', 'TRANSPORTES, FLETES Y ACARREOS', true, NOW(), NOW()),
(gen_random_uuid(), '23355001', 'SERVICIOS PUBLICOS', true, NOW(), NOW()),
(gen_random_uuid(), '23355501', 'SEGUROS', true, NOW(), NOW()),
(gen_random_uuid(), '23359501', 'OTROS', true, NOW(), NOW()),
(gen_random_uuid(), '23359502', 'CUENTA PUENTE CONCILIACION BANCOS', true, NOW(), NOW()),
(gen_random_uuid(), '23359503', 'OTROS DEL EXTERIOR', true, NOW(), NOW()),
(gen_random_uuid(), '23359599', 'NIIF - AJUSTE ACREEDORES DEL EXTERIOR', true, NOW(), NOW());

-- Note: This is the first batch. Run in batches to avoid command length limits.
