-- Script de inserción de Cuentas Auxiliares
-- Generado automáticamente desde Cuentax.txt
-- Total de cuentas: 851

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '14050101', 'MATERIAS PRIMAS', true, NOW(), NOW()),
    (gen_random_uuid(), '14050501', 'MATERIAS PRIMAS', true, NOW(), NOW()),
    (gen_random_uuid(), '14100505', 'PRODUCTO EN PROCESO MP', true, NOW(), NOW()),
    (gen_random_uuid(), '14100510', 'PRODUCTO EN PROCESO MOD', true, NOW(), NOW()),
    (gen_random_uuid(), '14100515', 'PRODUCTO EN PROCESO CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '14101005', 'PROD. EN PROC ORDENES ABIERTA MP', true, NOW(), NOW()),
    (gen_random_uuid(), '14101010', 'PROD. EN PROC ORDENES ABIERTA MOD', true, NOW(), NOW()),
    (gen_random_uuid(), '14101015', 'PROD. EN PROC ORDENES ABIERTA CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '14280501', 'PLATANO', true, NOW(), NOW()),
    (gen_random_uuid(), '14280502', 'PLANTACIONES DE CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '14301001', 'PRODUCTOS TERMINADOS MP', true, NOW(), NOW()),
    (gen_random_uuid(), '14301002', 'PRODUCTOS TERMINADOS MOD', true, NOW(), NOW()),
    (gen_random_uuid(), '14301003', 'PRODUCTOS TERMINADOS CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '14301004', 'INVENTARIO PRODUCTO DEFECTUOSO', true, NOW(), NOW()),
    (gen_random_uuid(), '14350101', 'MERCANCIA NO FABRICADA POR LA EMPRESA', true, NOW(), NOW()),
    (gen_random_uuid(), '14350102', 'IMPUESTO AL CONSUMO', true, NOW(), NOW()),
    (gen_random_uuid(), '14350103', 'BONOS', true, NOW(), NOW()),
    (gen_random_uuid(), '14350104', 'UTENSILIOS MUEBLES-ENSERES Y REPUESTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '14350105', 'IMPUESTO IBUA BEBIDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '14550101', 'DOTACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '14600101', 'EMPAQUES Y EMBALAJES', true, NOW(), NOW()),
    (gen_random_uuid(), '14659001', 'MERCANCIA EN TRANSITO', true, NOW(), NOW()),
    (gen_random_uuid(), '14990501', 'PUENTE SALDOS INICIALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15040501', 'URBANOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15041001', 'RURALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15080501', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15080502', 'CONSTRUCCIONES Y EDIFICACIONES FABRICA', true, NOW(), NOW()),
    (gen_random_uuid(), '151201001', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15120501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15160501', 'LOCALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15160597', 'REVALORIZACION LOCALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15160598', 'DETERIORO LOCALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15162001', 'FABRICAS Y PLANTAS INDUSTRIALES', true, NOW(), NOW()),
    (gen_random_uuid(), '15162097', 'REVALORIZACION FABRICA', true, NOW(), NOW()),
    (gen_random_uuid(), '15162098', 'DETERIORO FABRICA', true, NOW(), NOW()),
    (gen_random_uuid(), '15200102', 'MAQUINARIA Y EQUIPO EN COMODATO', true, NOW(), NOW()),
    (gen_random_uuid(), '15200103', 'MAQUINARIA Y EQUIPO ADQUIRIDA EN LEASING', true, NOW(), NOW()),
    (gen_random_uuid(), '15200197', 'REVALORIZACION MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15200198', 'DETERIORO MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15200199', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15280501', 'EQUIPO DE PROCESAMIENTO DE DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15280597', 'REVALORIZACION  EQUIP PROCES. DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15280598', 'DETERIORO EQUIP PROCES. DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15280599', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15281001', 'EQUIPO DE TELECOMUNICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15281097', 'REVALORIZACION EQUIP TELECOMUNICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15281098', 'DETERIORO EQUIP TELECOMUNICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15281099', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15400501', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '15400597', 'REVALORIZACION FLOTA Y EQUIPO DE TRANSP.', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '15400598', 'DETERIORO FLOTA Y EQUIPO DE TRANSP.', true, NOW(), NOW()),
    (gen_random_uuid(), '15400599', 'IVA EN ACTIVOS FIJOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15640501', 'CULTIVOS EN DESARROLLO', true, NOW(), NOW()),
    (gen_random_uuid(), '15640502', 'CULTIVOS EN DESARROLLO - INSUMOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15640503', 'CULTIVOS EN DESARROLLO-COMPRA HERRAMIEN.', true, NOW(), NOW()),
    (gen_random_uuid(), '15640504', 'CULTIVOS EN DESARROLLO - TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '156499', 'CULTIVOS EN DESARROLLO - OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '15880501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15881001', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '15881501', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '15881501-1', 'EQUIPO COMPUTACION YCOMUNICACION SIN IVA', true, NOW(), NOW()),
    (gen_random_uuid(), '15883001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '15887001', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15920501', 'CONSTRUCCIONES Y  EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15921001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15921501', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '15922001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '15923501', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '15990801', 'URBANOS', true, NOW(), NOW()),
    (gen_random_uuid(), '15991601', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '15992001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '15992801', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '15994001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '16350101', 'LICENCIA INVIMA', true, NOW(), NOW()),
    (gen_random_uuid(), '16350201', 'LICENCIA SIESA', true, NOW(), NOW()),
    (gen_random_uuid(), '17052001', 'SEGUROS Y FIANZAS', true, NOW(), NOW()),
    (gen_random_uuid(), '17059501', 'GASTOS PAGADOS POR ANTICIPADO', true, NOW(), NOW()),
    (gen_random_uuid(), '17100801', 'MEJORA A PROPIEDAD AJENA T. NUEVAS', true, NOW(), NOW()),
    (gen_random_uuid(), '17102801', 'CONSTRIBUCIONES Y AFILIACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '17103201', 'CAPACITACION DE PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '17104001', 'LICENCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '17104401', 'PUBLICIDAD, PROPAGANDA Y PROMOCION', true, NOW(), NOW()),
    (gen_random_uuid(), '17106001', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '17109501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '17109502', 'CANON VARIABLE - LOCALES', true, NOW(), NOW()),
    (gen_random_uuid(), '17109503', 'ENERGIA', true, NOW(), NOW()),
    (gen_random_uuid(), '18959501', 'IVA RETENIDO EN VENTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '19100801', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '19101201', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '19101601', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '19102001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '19103201', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '23300101', 'ORDENES DE COMPRA POR UTILIZAR', true, NOW(), NOW()),
    (gen_random_uuid(), '23351501', 'LIBROS, SUSCRIP, PERIODICOS Y REVISTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23352001', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '23352501', 'HONORARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23353001', 'SERVICIOS TECNICOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23353501', 'SERVICIOS DE MANTENIMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '23354001', 'ARRENDAMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '23354501', 'TRANSPORTES, FLETES Y ACARREOS', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '23355001', 'SERVICIOS PUBLICOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23355501', 'SEGUROS', true, NOW(), NOW()),
    (gen_random_uuid(), '23359501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '23359502', 'CUENTA PUENTE CONCILIACION BANCOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23359503', 'OTROS DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '23359599', 'NIIF - AJUSTE ACREEDORES DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '23550501', 'ACCIONISTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23551001', 'DIVIDENDOS DECRETADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23600501', 'DIVIDENDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23650501', 'SALARIOS Y PAGOS LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '23650502', 'RETENCION INDEPENDIENTES ART 383', true, NOW(), NOW()),
    (gen_random_uuid(), '23651001', 'RETENCION EN DIVIDENDOS Y/O PARTICIPACIO', true, NOW(), NOW()),
    (gen_random_uuid(), '23651501', 'HONORARIOS 11% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23651502', 'HONORARIOS 10% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23651503', 'HONORARIOS 3.5% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23651504', 'CONTRATO DE CONSULTORIA E ING 6%', true, NOW(), NOW()),
    (gen_random_uuid(), '23651505', 'HONORARIOS 11% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652001', 'COMISIONES 11% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23652002', 'COMISIONES 10% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652003', 'COMISIONES 11% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652501', 'SERVICIOS GENERALES 6% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652502', 'SERVICIOS TRANSPORTE 1% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23652503', 'SERVICIOS DE ASEO Y VIGILANCIA 2% P. JUR', true, NOW(), NOW()),
    (gen_random_uuid(), '23652504', 'SERVICIOS GENERALES 4% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23652505', 'SERVIC HOTELES, REST. Y HOSP 3.5% P.JURI', true, NOW(), NOW()),
    (gen_random_uuid(), '23652506', 'CONTRATOS DE CONSTR BN INMUEB 2% P.JURID', true, NOW(), NOW()),
    (gen_random_uuid(), '23652507', 'SERVICIOS TEMPORALES DE EMPLEO 1% P.JURI', true, NOW(), NOW()),
    (gen_random_uuid(), '23652508', 'SERVICIOS ASEO Y VIGIL. 2%(AIU 10%)P. JU', true, NOW(), NOW()),
    (gen_random_uuid(), '23652509', 'SERVICIOS INTEGRALES DE SALUD 2% P.JURID', true, NOW(), NOW()),
    (gen_random_uuid(), '23652511', 'SERVICIOS TRANSPORTE 1% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652512', 'SERVICIOS GENERALES 4% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23652513', 'SERVIC HOTELES, REST. Y HOSP 3.5% P.NATU', true, NOW(), NOW()),
    (gen_random_uuid(), '23652514', 'CONTRATOS DE CONSTR BN INMUEB 2% P.NATU', true, NOW(), NOW()),
    (gen_random_uuid(), '23652515', 'SERVICIOS TRANS NAL DE PASAJEROS 3.5% PN', true, NOW(), NOW()),
    (gen_random_uuid(), '23652516', 'SERVICIOS LICENCIAMIENTO SOFTW PJ 3.5%', true, NOW(), NOW()),
    (gen_random_uuid(), '23653001', 'ARRENDAMIENTOS MUEBLES 4% PER. JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23653003', 'ARRENDAM. INMUEBLES R 3.5% P. JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23653004', 'ARRENDAMIENTOS MUEBLES 4% PER. NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23653005', 'ARRENDAM. INMUEBLES R 3.5% P. NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23654001', 'COMPRAS GENERALES 2.5% P. JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23654002', 'COMPRAS CAFE PERGAMINO O CEREZA 0.5% P.J', true, NOW(), NOW()),
    (gen_random_uuid(), '23654003', 'COMPRA COMBUS. Y DERIV PETROLEO 0.1% P.J', true, NOW(), NOW()),
    (gen_random_uuid(), '23654004', 'COMPRAS GENERALES 3.5% PERSONA NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23654005', 'COMPRAS GENERALES 1.5% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23654006', 'COMPRAS VEHICULO 1% PERSONA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '23654007', 'COMPRAS GENERALES 2.5% P. NATURAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23654008', 'COMPRAS CAFE PERGAMINO O CEREZA 0.5% P.N', true, NOW(), NOW()),
    (gen_random_uuid(), '23654009', 'RETEFUENTE REGALIAS 2.5% PJ', true, NOW(), NOW()),
    (gen_random_uuid(), '23655001', 'RETENCION SERVICIOS EXT (OJO NO USAR)', true, NOW(), NOW()),
    (gen_random_uuid(), '23655002', 'RETENCION DE COMPRAS  DEL EXTERIOR', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '23655003', 'RETENCION DE SERVICIOS DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '23656501', 'POR IMPUESTO DE TIMBRE', true, NOW(), NOW()),
    (gen_random_uuid(), '23657001', 'INTERESES O RENDIMIENTOS FINANCIEROS 7%', true, NOW(), NOW()),
    (gen_random_uuid(), '23657501', 'AUTORRENCION DEL IMPUESTO SOBRE LA RENTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23657502', 'AUTORETENCION', true, NOW(), NOW()),
    (gen_random_uuid(), '23657503', 'AUTORRENCION RST', true, NOW(), NOW()),
    (gen_random_uuid(), '23659001', 'RETENCION PAGADA', true, NOW(), NOW()),
    (gen_random_uuid(), '23677001', 'RETEIVA COMPRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23677002', 'RETEIVA SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23677003', 'RETEIVA HONORARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23677004', 'RETEIVA SERVICIOS EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '23677005', 'RETEIVA REG. SIMPLE DE TRIBUTA COMPRA', true, NOW(), NOW()),
    (gen_random_uuid(), '23677006', 'RETEIVA REG. SIMPLE DE TRIBUTA SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23677007', 'RETEIVA COMPRAS EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '23677101', 'RETEIVA AL REG SIMPLIFICADO COMPRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23677102', 'RETEIVA AL REG SIMPLIFICADO SERVICIO', true, NOW(), NOW()),
    (gen_random_uuid(), '23679001', 'PAGO DE RETEIVA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680208', 'RETE ICA COMPRAS 11.04 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680209', 'RETE ICA COMPRAS 3.6 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680211', 'RETE ICA COMPRAS 3.8 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680212', 'RETE ICA COMPRAS 7 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680213', 'RETE ICA COMPRAS 4.5 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680215', 'RETE ICA COMPRAS 10 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680216', 'RETE ICA COMPRAS 4.815 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680217', 'RETE ICA COMPRAS 7.49 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680307', 'RETE ICA SERVICIOS 7.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680311', 'RETE ICA SERVICIOS 13.8 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680312', 'RETE ICA SERVICIOS 9.66 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680313', 'RETE ICA SERVICIOS 6.9 BGTA CONS PROFES', true, NOW(), NOW()),
    (gen_random_uuid(), '23680318', 'RETE ICA SERVICIOS 8.0 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680319', 'RETE ICA SERVICIOS 3.6 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680320', 'RETE ICA SERVICIOS 8.66 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680321', 'RETE ICA SERVICIOS 4.14 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680322', 'RETE ICA SERVICIOS 7.36 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680323', 'RETE ICA COMPRAS 5.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680326', 'RETE ICA SERVICIOS 7.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680327', 'RETE ICA SERVICIOS 10.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680328', 'RETE ICA SERVICIOS 3.5 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680329', 'RETE ICA SERVICIOS 6,9 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680330', 'RETE ICA SERVICIOS 4.5 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680331', 'RETE ICA SERVICIOS 11.04 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680333', 'RETE ICA SERVICIOS 9.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680335', 'RETE ICA SERVICIOS 4.815 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680336', 'RETE ICA SERVICIOS 8.56 CARTAGENA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680337', 'RETE ICA SERVICIOS 12.5 BARRANQUILLA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680338', 'RETE ICA SERVICIOS 9.0 PEREIRA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680339', 'RETE ICA SERVICIOS 10 CALI', true, NOW(), NOW()),
    (gen_random_uuid(), '23680340', 'RETE ICA SERVICIOS 8.0 FILANDIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680341', 'RETE ICA SERVICIOS 10 SALENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '23680342', 'RETE ICA SERVICIOS 5.0 SANTA ROSA', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '23680343', 'RETE ICA SERVICIOS 5.0 VILLA MARIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680344', 'RETE ICA SERVICIOS 10 TUNJA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680345', 'RETE ICA SERVICIOS 8.0 BARRANQUILLA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680346', 'RETE ICA SERVICIOS 6.6 CALI', true, NOW(), NOW()),
    (gen_random_uuid(), '23680347', 'RETE ICA SERVICIOS 12.05 PEREIRA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680348', 'RETE ICA SERVICIOS 8.0 SALENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '23680349', 'RETE ICA SERVICIOS 9.0 FILANDIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680350', 'RETE ICA SERVICIOS 6.0 VILLAMARIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680351', 'RETE ICA SERVICIOS 7.60 BOGOTA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680352', 'RETE ICA SERVICIOS 3.3 CALI', true, NOW(), NOW()),
    (gen_random_uuid(), '23680353', 'RETEICA SERVICIOS 10 PEREIRA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680354', 'RETEICA SERVICIOS 8.0 ARMENIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23680401', 'AUTORRETENCION ICA ACT. 3.6', true, NOW(), NOW()),
    (gen_random_uuid(), '23680402', 'AUTORRETENCION ICA ACT. 10', true, NOW(), NOW()),
    (gen_random_uuid(), '23689001', 'RETEICA PAGADO', true, NOW(), NOW()),
    (gen_random_uuid(), '23690101', 'CREE 0.40%', true, NOW(), NOW()),
    (gen_random_uuid(), '23699001', 'PAGO RETENCION CREE', true, NOW(), NOW()),
    (gen_random_uuid(), '23700501', 'APORTES A EPS', true, NOW(), NOW()),
    (gen_random_uuid(), '23700601', 'APORTES A RIESGOS PROFESIONALES', true, NOW(), NOW()),
    (gen_random_uuid(), '23701001', 'APORTES AL ICBF, SENA Y CCF', true, NOW(), NOW()),
    (gen_random_uuid(), '23703001', 'LIBRANZAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23704501', 'APORTES A FONDOS DE PENSIONES Y CESANTIA', true, NOW(), NOW()),
    (gen_random_uuid(), '23704502', 'APORTES FONDO DE PENSIONES VOLUNTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23704503', 'APORTES FONDOS AFC', true, NOW(), NOW()),
    (gen_random_uuid(), '23704504', 'EMBARGO JUDICIAL', true, NOW(), NOW()),
    (gen_random_uuid(), '23709501', 'DONACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '23800501', 'DEPOSITARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '23803001', 'FONDOS DE CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '23803002', 'FONDOS DE PENSION', true, NOW(), NOW()),
    (gen_random_uuid(), '23809501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '25050101', 'SALARIOS POR PAGAR', true, NOW(), NOW()),
    (gen_random_uuid(), '25100101', 'CESANTIAS CONSOLIDADAS', true, NOW(), NOW()),
    (gen_random_uuid(), '25150101', 'INTERESES SOBRE CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '25200101', 'PRIMA DE SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '25250501', 'VACACIONES CONSOLIDADAS', true, NOW(), NOW()),
    (gen_random_uuid(), '25309501', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '26109501', 'SALUD', true, NOW(), NOW()),
    (gen_random_uuid(), '26109502', 'PENSION', true, NOW(), NOW()),
    (gen_random_uuid(), '26109503', 'FONDO SOLIDARIDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '26150501', 'DE RENTA Y COMPLEMENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '27054001', 'CONSIGNACIONES PENDIENTES POR IDENTIFICA', true, NOW(), NOW()),
    (gen_random_uuid(), '27054002', 'MERCANCIA EN TRANSITO YA VENDIDA-BONOS', true, NOW(), NOW()),
    (gen_random_uuid(), '27059501', 'OTROS * PROPINAS', true, NOW(), NOW()),
    (gen_random_uuid(), '27059502', 'OTROS *VENTAS DIFERIDAS EXPORTACION*', true, NOW(), NOW()),
    (gen_random_uuid(), '27059503', 'OTROS *VENTAS DIFERIDAS NACIONALES*', true, NOW(), NOW()),
    (gen_random_uuid(), '28050501', 'NACIONALES', true, NOW(), NOW()),
    (gen_random_uuid(), '28050502', 'DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '28059501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '31050501', 'CAPITAL AUTORIZADO', true, NOW(), NOW()),
    (gen_random_uuid(), '33050501', 'RESERVA LEGAL', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '33051601', 'ACCIONES PROPIAS READQUIRIDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '34050501', 'DE CAPITAL SOCIAL', true, NOW(), NOW()),
    (gen_random_uuid(), '34051001', 'DE SUPERAVIT DE CAPITAL', true, NOW(), NOW()),
    (gen_random_uuid(), '34052001', 'RESULTADOS DE EJERCICIOS ANTERIORES', true, NOW(), NOW()),
    (gen_random_uuid(), '35050101', 'PAGO DIVIDENDOS DECRETADOS EN ACCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '36050101', 'UTILIDAD DEL EJERCICIO', true, NOW(), NOW()),
    (gen_random_uuid(), '37050101', 'UTILIDADES ACUMULADAS', true, NOW(), NOW()),
    (gen_random_uuid(), '37050102', 'UTILIDADES ACUMULADAS AÑO 2016', true, NOW(), NOW()),
    (gen_random_uuid(), '37050103', 'UTILIDADES ACUMULADAS AÑO 2020', true, NOW(), NOW()),
    (gen_random_uuid(), '37050104', 'UTILIDADES ACUMULADAS AÑO 2021', true, NOW(), NOW()),
    (gen_random_uuid(), '37050105', 'UTILIDADES ACUMULADAS AÑO 2022', true, NOW(), NOW()),
    (gen_random_uuid(), '37050199', 'CUADRE SALDOS INICIALES', true, NOW(), NOW()),
    (gen_random_uuid(), '37900101', 'AJUSTE POR PRIMERA VEZ NIIF', true, NOW(), NOW()),
    (gen_random_uuid(), '38100801', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '38101201', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '38101601', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '38102001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '38103201', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '41201301', 'CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '41201302', 'DERIVADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41201303', 'INGRESOS POR VENTAS DIFERIDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41201304', 'DESCUENTOS COMERCIALES CONCEDIDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41201305', 'DESCUENTOS EXTRAPACK', true, NOW(), NOW()),
    (gen_random_uuid(), '41359501', 'TIENDAS DE CAFE - RESTAURANTE', true, NOW(), NOW()),
    (gen_random_uuid(), '41359502', 'ING. SOUVENIRS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '41359503', 'INGRESO INSUMOS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '41359504', 'INGRESOS NO GRAVADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359505', 'OTROS INGRESOS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '41359601', 'LÍNEA DE PRODUCTOS CORPORATIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359602', 'ESCUELA DE CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '41359603', 'KITS O PRODUCTOS CORPORATIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359604', 'PRODUCCIÓN ESPECIAL', true, NOW(), NOW()),
    (gen_random_uuid(), '41359605', 'LOGISTICA', true, NOW(), NOW()),
    (gen_random_uuid(), '41359701', 'EXPORTACIONES CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '41359702', 'EXPORTACIONES GALLETAS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359703', 'EXPORTACIONES AREQUIPE', true, NOW(), NOW()),
    (gen_random_uuid(), '41359704', 'EXPORTACIONES MERMELADA', true, NOW(), NOW()),
    (gen_random_uuid(), '41359705', 'EXPORTACIONES MERENGUITOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359706', 'ING SOUVENIRS POSICIONAM. DE MARCA EXPOR', true, NOW(), NOW()),
    (gen_random_uuid(), '41359707', 'FLETES Y SEGUROS EXPORTACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '41359708', 'EMPAQUES Y EMBALAJES EXPORTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '41359709', 'GASTOS ADUANEROS', true, NOW(), NOW()),
    (gen_random_uuid(), '41359710', 'DOCUMENTO DE EXPORTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '41359711', 'EXPORTACIONES CAFE VERDE', true, NOW(), NOW()),
    (gen_random_uuid(), '41600501', 'ESCUELA DE CAFÉ', true, NOW(), NOW()),
    (gen_random_uuid(), '41750101', 'CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '41750102', 'DERIVADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '41750103', 'DEV. SOUVENIRS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '41750104', 'DEVOLUCIONES EN VENTAS OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '41750105', 'DEVOL.TIENDAS DE CAFE - RESTAURANTE', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '41750106', 'DEV. INSUMOS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '41750107', 'DEVOLUCIONES VETNAS DIFERIDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '41750108', 'DEVOLUCIONES EXPORTACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '41750109', 'DEVOLUCION DE MERCANCIAS NO RECOGIDA', true, NOW(), NOW()),
    (gen_random_uuid(), '42053501', 'PLATANO', true, NOW(), NOW()),
    (gen_random_uuid(), '42100501', 'INTERESES', true, NOW(), NOW()),
    (gen_random_uuid(), '42100502', 'INTERESES FIDURENTA FIJO PLAZA 1621', true, NOW(), NOW()),
    (gen_random_uuid(), '42100503', 'INTERESES FIDURENTA  3625', true, NOW(), NOW()),
    (gen_random_uuid(), '42100504', 'INTERESES FIDUCUENTA 2676', true, NOW(), NOW()),
    (gen_random_uuid(), '42100505', 'INTERESES FIDUCUENTA 0389', true, NOW(), NOW()),
    (gen_random_uuid(), '42100506', 'INTERESES FIDUCUENTA 0157', true, NOW(), NOW()),
    (gen_random_uuid(), '42100507', 'INTERESES CDTS', true, NOW(), NOW()),
    (gen_random_uuid(), '42100508', 'INTERESES A SOCIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42100509', 'INTERESES CTA SCOTIABANK 22060', true, NOW(), NOW()),
    (gen_random_uuid(), '42100510', 'INTERESES MONEDA EXTRANJERA', true, NOW(), NOW()),
    (gen_random_uuid(), '42100511', 'INTERESES CDTS 81433328', true, NOW(), NOW()),
    (gen_random_uuid(), '42100512', 'INTERESES FIDURENTA 9050', true, NOW(), NOW()),
    (gen_random_uuid(), '42100513', 'INTERESES CDT PROTEGIDO', true, NOW(), NOW()),
    (gen_random_uuid(), '42100514', 'INTERESES  ALLIANZA', true, NOW(), NOW()),
    (gen_random_uuid(), '42100515', 'INTERESES  BONOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42100516', 'INTERESES DE PRESTAMOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42100517', 'INTERESES FIDUCUENTA DAVIVIENDA', true, NOW(), NOW()),
    (gen_random_uuid(), '42102001', 'DIFERENCIA EN CAMBIO', true, NOW(), NOW()),
    (gen_random_uuid(), '42104001', 'DESCUENTOS COMERCIALES CONDICIONADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42109501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '42201001', 'ARRENDAMIENTO LOCAL', true, NOW(), NOW()),
    (gen_random_uuid(), '42201501', 'MAQUINAS ESPRESSO', true, NOW(), NOW()),
    (gen_random_uuid(), '42358001', 'FLETES', true, NOW(), NOW()),
    (gen_random_uuid(), '42505001', 'REINTEGRO DE OTROS COSTOS Y GASTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42550501', 'POR SINIESTRO', true, NOW(), NOW()),
    (gen_random_uuid(), '42552001', 'DAÑO EMERGENTE COMPAÑIAS DE SEGUROS', true, NOW(), NOW()),
    (gen_random_uuid(), '42552501', 'POR PERDIDA DE MERCANCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '42554001', 'POR INCAPACIDADES', true, NOW(), NOW()),
    (gen_random_uuid(), '42559501', 'REINTEGRO DE MULTAS Y SANCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '42800501', 'INGRESOS POR SUBVENCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '42950501', 'APROVECHAMIENTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '42951101', 'INGRESOS POR INVESTIGACION Y DESARROLLO', true, NOW(), NOW()),
    (gen_random_uuid(), '42958101', 'AJUSTE AL PESO', true, NOW(), NOW()),
    (gen_random_uuid(), '42959501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '42959502', 'SOBRANTES DE INVENTARIO FISICO', true, NOW(), NOW()),
    (gen_random_uuid(), '51050301', 'SALARIO INTEGRAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51050601', 'SUELDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51051501', 'HORAS EXTRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51051502', 'RECARGO DOMINICALES Y FESTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51052701', 'AUXILIO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '51053001', 'CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51053301', 'INTERESES A LAS CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51053601', 'PRIMA DE SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51053901', 'VACACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51054501', 'AUXILIOS', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '51054502', 'AUXILIO CALAMIDAD POR LIBERALIDAD EMPRES', true, NOW(), NOW()),
    (gen_random_uuid(), '51054503', 'AUXILIO PARA COMPRA DE LENTES', true, NOW(), NOW()),
    (gen_random_uuid(), '51054504', 'AUXILIO INCENTIVOS POR ESTUDIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51054505', 'AUXILIO PARA TRASLADO DE CIUDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '51054506', 'AUXILIO PBONO MATERNIDAD / PATERNIDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '51054507', 'AUXILIO FUNERARIO', true, NOW(), NOW()),
    (gen_random_uuid(), '51054508', 'AUXILIO ALIMENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51054801', 'BONIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51054802', 'BONIFICACIONES POR LIBERALIDAD DE LA EMP', true, NOW(), NOW()),
    (gen_random_uuid(), '51054808', 'AUXILIO ALIMENTARIO', true, NOW(), NOW()),
    (gen_random_uuid(), '51055101', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '51055102', 'AUXILIO ARREGLO DE DOTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51056001', 'INDEMNIZACIONES LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '51056301', 'CAPACITACION AL PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51056601', 'GASTOS DEPORTIVOS Y DE RECREACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51056801', 'APORTES DE RIESGOS PROFESIONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51056901', 'APORTES A EPS', true, NOW(), NOW()),
    (gen_random_uuid(), '51057001', 'APORTES A FONDO DE PENSIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51057201', 'APORTES CAJAS DE COMPENSACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51057501', 'APORTES A ICBF', true, NOW(), NOW()),
    (gen_random_uuid(), '51057801', 'SENA', true, NOW(), NOW()),
    (gen_random_uuid(), '51058401', 'GASTOS MEDICOS Y DROGAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51101501', 'HONORARIOS AUDITORIA EXTERNA', true, NOW(), NOW()),
    (gen_random_uuid(), '51102001', 'HONORARIOS AVALUOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51102501', 'ASESORIA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '51103001', 'ASESORIA FINANCIERA', true, NOW(), NOW()),
    (gen_random_uuid(), '51103501', 'ASESORIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '51109501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51109502', 'HONORARIOS PRESTADOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '51109503', 'IVA MAYOR VALOR DEL GASTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51109504', 'HONORARIOS PRESTADOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '51150501', 'INDUSTRIA Y COMERCIO', true, NOW(), NOW()),
    (gen_random_uuid(), '51151001', 'DE TIMBRES', true, NOW(), NOW()),
    (gen_random_uuid(), '51151501', 'A LA PROPIEDAD RAIZ', true, NOW(), NOW()),
    (gen_random_uuid(), '51152001', 'DERECHOS SOBRE INSTRUMENTOS PUBLICOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51152501', 'DE VALORIZACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51153001', 'IMPUESTO DE TURISMO', true, NOW(), NOW()),
    (gen_random_uuid(), '51154001', 'DE VEHICULOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51157001', 'IVA DESCONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '51159501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51159502', 'IMPUESTO SOBRETASA IMPTO EQUIDAD CREE', true, NOW(), NOW()),
    (gen_random_uuid(), '51201001', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51201501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '51202501', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51204001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '51250501', 'CONTRIBUCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51251001', 'AFILIACIONES Y SOSTENIMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51251001-1', 'AFILIACIONES Y SOSTENIMIENTO SIN IVA', true, NOW(), NOW()),
    (gen_random_uuid(), '51300501', 'MANEJO', true, NOW(), NOW()),
    (gen_random_uuid(), '51301001', 'CUMPLIMIENTO', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '51301501', 'CORRIENTE DEBIL', true, NOW(), NOW()),
    (gen_random_uuid(), '51301601', 'SEGURO DE ACTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51302001', 'VIDA COLECTIVA', true, NOW(), NOW()),
    (gen_random_uuid(), '51302501', 'INCENDIO', true, NOW(), NOW()),
    (gen_random_uuid(), '51303001', 'TERREMOTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51303501', 'SUSTRACCION Y HURTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51304001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '51306001', 'RESPONSABILIDAD CIVIL Y EXTRACONTRACTUAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51307001', 'ROTURA DE MAQUINARIA', true, NOW(), NOW()),
    (gen_random_uuid(), '51307501', 'OBLIGATORIO ACCIDENTE DE TRANSITO', true, NOW(), NOW()),
    (gen_random_uuid(), '51308501', 'SEGURO TRANSPORTE MERCANCIA EXPORTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51309501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51309502', 'SEGURO TODO RIESGO', true, NOW(), NOW()),
    (gen_random_uuid(), '51350501', 'ASEO Y VIGILANCIA', true, NOW(), NOW()),
    (gen_random_uuid(), '51351001', 'TEMPORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '51351501', 'ASISTENCIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '51352001', 'PROCESAMIENTO ELECTRONICO DE DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51352501', 'ACUEDUCTO Y ALCANTARILLADO', true, NOW(), NOW()),
    (gen_random_uuid(), '51353001', 'ENERGIA', true, NOW(), NOW()),
    (gen_random_uuid(), '51353002', 'ENERGIA SOLAR', true, NOW(), NOW()),
    (gen_random_uuid(), '51353501', 'TELEFONO', true, NOW(), NOW()),
    (gen_random_uuid(), '51354001', 'CORREO, PORTES Y TELEGRAMAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51354501', 'FAX Y TELEX', true, NOW(), NOW()),
    (gen_random_uuid(), '51355001', 'TRANSPORTES, FLETES Y ACARREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51355501', 'GAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51356001', 'PUBLICIDAD, PROPAGANDA Y PROMI', true, NOW(), NOW()),
    (gen_random_uuid(), '51359001', 'INTERNET', true, NOW(), NOW()),
    (gen_random_uuid(), '51359501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51359502', 'OTROS * SERVICIOS VIRTUALES', true, NOW(), NOW()),
    (gen_random_uuid(), '51359503', 'IVA MAYOR VALOR DEL GASTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51400501', 'NOTARIALES', true, NOW(), NOW()),
    (gen_random_uuid(), '51401001', 'REGISTRO MERCANTIL', true, NOW(), NOW()),
    (gen_random_uuid(), '51401501', 'TRAMITES Y LICENCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51402001', 'ADUANEROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51409501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51451501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '51452001', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '51452501', 'EQUIPO DE COMPUTACION Y COMUNICACIÓN', true, NOW(), NOW()),
    (gen_random_uuid(), '51454001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '51500501', 'INSTALACIONES ELECTRICAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51501001', 'ARREGLOS ORNAMENTALES', true, NOW(), NOW()),
    (gen_random_uuid(), '51501501', 'REPARACIONES LOCATIVAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51502001', 'OBRAS DE ARTE', true, NOW(), NOW()),
    (gen_random_uuid(), '515095', 'OTROS INSTALACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51550501', 'ALOJAMIENTO Y MANUTENCION', true, NOW(), NOW()),
    (gen_random_uuid(), '51551501', 'PASAJES AEREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51552001', 'PASAJES TERRESTRES', true, NOW(), NOW()),
    (gen_random_uuid(), '51559501', 'GASTOS DE DESPLAZAMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '51600501', 'DEPRECIACIONES CONSTRUCCIONES Y EDIFI.', true, NOW(), NOW()),
    (gen_random_uuid(), '51601001', 'DEPRECIACION MAQUINARIA Y EQUIPO', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '51601501', 'DEPRECIACION EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '51602001', 'DEPRECIACION  EQ. DE COMPUTO Y COMUNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '51603501', 'DEPRECIACION FLOTA Y EQUIPO DE TRANS.', true, NOW(), NOW()),
    (gen_random_uuid(), '51651001', 'INTANGIBLES', true, NOW(), NOW()),
    (gen_random_uuid(), '51651002', 'LICENCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51651099', 'NIIF - AMORTIZACIÓN DE INTANGIBLES', true, NOW(), NOW()),
    (gen_random_uuid(), '51651501', 'CARGOS DIFERIDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51651502', 'CAPACITACION DE PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51950501', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '51951001', 'LIBROS,SUSCRIPCIONES,PERIODICO', true, NOW(), NOW()),
    (gen_random_uuid(), '51951501', 'MUSICA AMBIENTAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51952001', 'GASTOS DE REPRESENTACION Y RELACIONES PU', true, NOW(), NOW()),
    (gen_random_uuid(), '51952501', 'ELEMENTOS DE ASEO Y CAFETERIA', true, NOW(), NOW()),
    (gen_random_uuid(), '51953001', 'UTILES, PAPELERIA Y FOTOCOPIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51953002', 'IMPRESOS - TIPOGRAFIA Y LITOGRAFIA', true, NOW(), NOW()),
    (gen_random_uuid(), '51953501', 'COMBUSTIBLES Y LUBRICANTES', true, NOW(), NOW()),
    (gen_random_uuid(), '51954001', 'ENVASES Y EMPAQUES', true, NOW(), NOW()),
    (gen_random_uuid(), '51954501', 'TAXIS Y BUSES', true, NOW(), NOW()),
    (gen_random_uuid(), '51955001', 'ESTAMPILLAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51956001', 'CASINO Y RESTAURANTE', true, NOW(), NOW()),
    (gen_random_uuid(), '51956501', 'PARQUEADEROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51959501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '51959502', 'SOBRANTES DE INVENTARIO FISICO', true, NOW(), NOW()),
    (gen_random_uuid(), '51959503', 'COMPRA EQU.MENORES,MUEBLES,ACCES Y UTENS', true, NOW(), NOW()),
    (gen_random_uuid(), '51959504', 'FALTANTES DE INVENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '51959505', 'OBSEQ, MUESTRAS,OFERTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '51959506', 'ELEMENTOS SALUD OCUPACIONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '51959508', 'GASTOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '51959510', 'PEAJE  - ADMINISTRATIVO', true, NOW(), NOW()),
    (gen_random_uuid(), '51991501', 'CONTRUCCIONES EN CURSO', true, NOW(), NOW()),
    (gen_random_uuid(), '51991502', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '51991503', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '51991504', 'EQUIPO DE COMUNICACIÓN Y COMPUTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '51991505', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52050301', 'SALARIO INTEGRAL', true, NOW(), NOW()),
    (gen_random_uuid(), '52050601', 'SUELDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52051501', 'HORAS EXTRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52051502', 'RECARGOS DOMINICALES Y FESTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52051801', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52052101', 'VIATICOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52052701', 'AUXILIO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52053001', 'CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52053301', 'INTERESES SOBRE CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52053601', 'PRIMA DE SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52053901', 'VACACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52054501', 'AUXILIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52054502', 'AUXILIO CALAMIDAD POR LIBERALIDAD EMPRES', true, NOW(), NOW()),
    (gen_random_uuid(), '52054503', 'AUXILIO PARA COMPRA DE LENTES', true, NOW(), NOW()),
    (gen_random_uuid(), '52054504', 'AUXILIO INCENTIVOS POR ESTUDIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52054505', 'AUXILIO PARA TRASLADO DE CIUDAD', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '52054506', 'AUXILIO BONO MATERNIDAD / PATERNIDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '52054507', 'AUXILIO FUNERARIO', true, NOW(), NOW()),
    (gen_random_uuid(), '52054508', 'AUXILIO ALIMENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52054801', 'BONIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52054802', 'BONIFICACIONES POR LIBERALIDAD DE LA EMP', true, NOW(), NOW()),
    (gen_random_uuid(), '52055101', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '52055102', 'AUXILIO ARREGLO DE DOTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52056001', 'INDEMNIZACIONES LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52056301', 'CAPACITACION AL PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '52056601', 'GASTOS DEPORTIVOS Y DE RECREACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52056801', 'APORTES A RIESGOS PROFESIONALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52056901', 'APORTES A EPS', true, NOW(), NOW()),
    (gen_random_uuid(), '52057001', 'APORTES A FONDOS DE PENSIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52057201', 'APORTES A CAJAS DE COMPENSACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52057501', 'APORTES ICBF', true, NOW(), NOW()),
    (gen_random_uuid(), '52057801', 'SENA', true, NOW(), NOW()),
    (gen_random_uuid(), '52058401', 'GASTOS MEDICOS Y DROGAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52059501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52101501', 'HONORARIOS AUDITORIA EXTERNA', true, NOW(), NOW()),
    (gen_random_uuid(), '52102001', 'HONORARIOS AVALUOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52102501', 'ASESORIA JURIDICA', true, NOW(), NOW()),
    (gen_random_uuid(), '52103501', 'ASESORIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '52109501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52109502', 'HONORARIOS PRESTADOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '52150501', 'INDUSTRIA Y COMERCIO', true, NOW(), NOW()),
    (gen_random_uuid(), '52151001', 'DE TIMBRES', true, NOW(), NOW()),
    (gen_random_uuid(), '52151501', 'IMPUESTO A LA PROPIEDAD RAIZ', true, NOW(), NOW()),
    (gen_random_uuid(), '52153001', 'IMPUESTO DE TURISMO', true, NOW(), NOW()),
    (gen_random_uuid(), '52154001', 'DE VEHICULOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52157001', 'IVA DESCONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '52159501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52201001', 'ARRENDAMIENTO CONSTRUCCIONES Y EDIFICACI', true, NOW(), NOW()),
    (gen_random_uuid(), '52201501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '52202501', 'EQUIPO DE COMUNICACION Y COMPUTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52204001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52209501', 'ARREND. STAND-GALERIAS-GONDOLA', true, NOW(), NOW()),
    (gen_random_uuid(), '52209502', 'ARRENDAMIENTOS MUEBLES OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52209503', 'IVA MAYOR VALOR DEL GASTO', true, NOW(), NOW()),
    (gen_random_uuid(), '52209504', 'ARRENDAMIENTO DE ESTIBAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52250501', 'CONTRIBUCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52251001', 'AFILIACIONES Y SOSTENIMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '52300501', 'MANEJO', true, NOW(), NOW()),
    (gen_random_uuid(), '52301001', 'CUMPLIMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '52301601', 'SEGURO DE ACTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52302001', 'VIDA COLECTIVA', true, NOW(), NOW()),
    (gen_random_uuid(), '52302501', 'INCENDIO', true, NOW(), NOW()),
    (gen_random_uuid(), '52304001', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52306001', 'RESPONSABILIDAD CIVIL Y EXTRACONTRACTUAL', true, NOW(), NOW()),
    (gen_random_uuid(), '52307501', 'OBLIGATORIO ACCIDENTE DE TRANSITO', true, NOW(), NOW()),
    (gen_random_uuid(), '52308501', 'SEGURO TRANSPORTE MERCANCIA EXPORTACION', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '52309501', 'SEGURO TRANSPORTE DE MERCANCIA', true, NOW(), NOW()),
    (gen_random_uuid(), '52309502', 'SEGURO TODO RIESGO', true, NOW(), NOW()),
    (gen_random_uuid(), '52350501', 'ASEO Y VIGILANCIA', true, NOW(), NOW()),
    (gen_random_uuid(), '52351001', 'TEMPORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52351501', 'ASISTENCIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '52352001', 'PROCESAMIENTO ELECTRONICO DE DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52352501', 'ACUEDUCTO Y ALCANTARILLADO', true, NOW(), NOW()),
    (gen_random_uuid(), '52353001', 'ENERGIA', true, NOW(), NOW()),
    (gen_random_uuid(), '52353002', 'ENERGIA SOLAR', true, NOW(), NOW()),
    (gen_random_uuid(), '52353501', 'TELEFONO', true, NOW(), NOW()),
    (gen_random_uuid(), '52354001', 'CORREO, PORTES Y TELEGRAMAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52354501', 'FAX Y TELEX', true, NOW(), NOW()),
    (gen_random_uuid(), '52355001', 'TRANSPORTES, FLETES Y ACARREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52355501', 'GAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52356001', 'PUBLICIDAD, PROPAGANDA Y PROMI', true, NOW(), NOW()),
    (gen_random_uuid(), '52356002', 'PUBLICIDAD EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '52359001', 'INTERNET', true, NOW(), NOW()),
    (gen_random_uuid(), '52359501', 'OTROS * ADMINISTRACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52359502', 'OTROS * SERVICIOS VIRTUALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52359503', 'SERVICIO DE REGALIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52500501', 'INSTALACIONES ELECTRICAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52501001', 'ARREGLOS ORNAMENTALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52501501', 'REPARACIONES LOCATIVAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52509501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52550501', 'ALOJAMIENTO Y MANUTENCION', true, NOW(), NOW()),
    (gen_random_uuid(), '52551501', 'PASAJES AEREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52552001', 'PASAJES TERRESTRES', true, NOW(), NOW()),
    (gen_random_uuid(), '52559501', 'GASTOS DE DESPLAZAMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '52600501', 'DEPRECIACION CONSTRUCCIONES Y EDIFICACIO', true, NOW(), NOW()),
    (gen_random_uuid(), '52601001', 'DEPRECIACION MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '52601501', 'DEPRCIACION EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '52602001', 'DEPRECIACION EQ. DE COMPUTO Y COMUNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '52603501', 'DEPRCIACION FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52651001', 'INTANGIBLES', true, NOW(), NOW()),
    (gen_random_uuid(), '52651002', 'LICENCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52651501', 'CARGOS DIFERIDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52651502', 'CAPACITACION DE PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '52651503', 'PUBLICIDAD, PROPAGANDA Y PROMOCION', true, NOW(), NOW()),
    (gen_random_uuid(), '52659501', 'OTRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52659502', 'MEJORA A PROPIEDAD AJENA T. NUEVAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52659503', 'REMODELACIONES TIENDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52659505', 'AMORTIZACION CANON ARRENDAMIENTO VARIABL', true, NOW(), NOW()),
    (gen_random_uuid(), '52950501', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '52951001', 'LIBROS, SUSCRIP, PERIODICOS Y REVISTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52952001', 'GASTOS DE REPRESENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '52952501', 'ELEMENTOS DE ASEO Y CAFETERIA', true, NOW(), NOW()),
    (gen_random_uuid(), '52953001', 'UTILES, PAPELERIA Y FOTOCOPIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52953002', 'IMPRESOS, LITOGRAFIA Y TIPOGRAFIA', true, NOW(), NOW()),
    (gen_random_uuid(), '52953501', 'COMBUSTIBLES Y LUBRICANTES', true, NOW(), NOW()),
    (gen_random_uuid(), '52953502', 'COMBUSTIBLES CAMIONETA ARK 853', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '52953503', 'COMBUSTIBLE CAMIONETA CLB 852', true, NOW(), NOW()),
    (gen_random_uuid(), '52954001', 'ENVASES Y EMPAQUES', true, NOW(), NOW()),
    (gen_random_uuid(), '52954501', 'TAXIS Y BUSES', true, NOW(), NOW()),
    (gen_random_uuid(), '52955001', 'ESTAMPILLAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52956001', 'CASINO Y RESTAURANTE', true, NOW(), NOW()),
    (gen_random_uuid(), '52956501', 'PARQUEADERO', true, NOW(), NOW()),
    (gen_random_uuid(), '52959501', 'DEGUST, OBSEQ, MUESTRAS,OFERTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959502', 'PEAJES', true, NOW(), NOW()),
    (gen_random_uuid(), '52959503', 'IMPULSO Y MERCADEO', true, NOW(), NOW()),
    (gen_random_uuid(), '52959504', 'FALTANTES DE INVENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959505', 'ANALISIS MICROBIOLOGICOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959506', 'COMPRA EQU.MENORES,MUEBLES,ACCES Y UTENS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959507', 'FERIAS Y EVENTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959508', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959509', 'GASTOS GERENCIALES', true, NOW(), NOW()),
    (gen_random_uuid(), '52959510', 'PERDIDA POR SINIESTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959511', 'DEPURACION BODEGAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959512', 'ELEMENTOS DESECHABLES', true, NOW(), NOW()),
    (gen_random_uuid(), '52959513', 'ELEMENTOS SALUD OCUPACIONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '52959518', 'OPERACION LOGISTICA CADENAS PAC', true, NOW(), NOW()),
    (gen_random_uuid(), '52959519', 'OPERACION EXTRAPACK CADENAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959520', 'OPERACION LOGISTICA CADENAS', true, NOW(), NOW()),
    (gen_random_uuid(), '52959521', 'IVA MAYOR VALOR DEL GASTO', true, NOW(), NOW()),
    (gen_random_uuid(), '52959522', 'N/A CARGUE Y DESCARGUE PRODUCTO COMERC', true, NOW(), NOW()),
    (gen_random_uuid(), '52959523', 'GASTOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '52959525', 'COBRO CROSSDOKING', true, NOW(), NOW()),
    (gen_random_uuid(), '529910', 'PROVISIÓN DEUDORES', true, NOW(), NOW()),
    (gen_random_uuid(), '52991002', 'DEUDORES', true, NOW(), NOW()),
    (gen_random_uuid(), '53050501', 'COSTO DE CHEQUERA', true, NOW(), NOW()),
    (gen_random_uuid(), '53050502', 'GTOS BANCARIOS DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '53051501', 'COMISIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53051502', 'COMISIONES BANCOS DEL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '53051503', 'CUOTA DE MANEJO', true, NOW(), NOW()),
    (gen_random_uuid(), '53052001', 'INTERESES', true, NOW(), NOW()),
    (gen_random_uuid(), '53052501', 'DIFERENCIA DE CAMBIO', true, NOW(), NOW()),
    (gen_random_uuid(), '53053501', 'DESCUENTOS COMERCIALES CONDICIONADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53059501', 'AJUSTE AL PESO', true, NOW(), NOW()),
    (gen_random_uuid(), '53059502', 'AJUSTE DIFERENCIA XENCO', true, NOW(), NOW()),
    (gen_random_uuid(), '53059503', 'OTROS GASTOS BANCARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53100501', 'VENTA DE INVERSIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53101501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '53101502', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '53101503', 'EQUIPO PROCESAMIENTO DATOS Y TELECOMUNIC', true, NOW(), NOW()),
    (gen_random_uuid(), '53101504', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '53101505', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53102501', 'VENTA DE OTROS ACTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53103001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '53103002', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '53103003', 'EQUIPO PROCESAMIENTO DATOS Y TELECOMUNIC', true, NOW(), NOW()),
    (gen_random_uuid(), '53103004', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '53103005', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53103501', 'RETIRO DE OTROS ACTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53104001', 'PERDIDA POR SINIESTRO', true, NOW(), NOW()),
    (gen_random_uuid(), '53109501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '53151501', 'COSTOS Y GASTOS DE EJERCICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53152001', 'IMPUESTOS ASUMIDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53152002', 'GRAVAMEN AL MOVIMIENTO FINANCIERO', true, NOW(), NOW()),
    (gen_random_uuid(), '53152003', 'IMPUESTOS ASUMIDOS IVA 5%', true, NOW(), NOW()),
    (gen_random_uuid(), '53152004', 'IMPUESTOS ASUMIDOS IVA 19%', true, NOW(), NOW()),
    (gen_random_uuid(), '53152005', 'IMPUESTOS ASUMIDOS IMPO 8%', true, NOW(), NOW()),
    (gen_random_uuid(), '53152006', 'IMPUESTOS ASUMIDOS ICUI', true, NOW(), NOW()),
    (gen_random_uuid(), '53159501', 'GASTOS DIVERSOS DIRECTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53159502', 'GASTOS DE REPRESENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '53159503', 'GASTOS NO DEDUCIBLES', true, NOW(), NOW()),
    (gen_random_uuid(), '53159504', 'GTOS NO DEDUCI SIN SOPORTE LEGALE VTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '53159505', 'GTOS NO DEDUCIB SIN SOPORTE LEGALE PDC', true, NOW(), NOW()),
    (gen_random_uuid(), '53159506', 'GTOS NO DEDUCIB SIN SOPORTE LEGAL ADMON', true, NOW(), NOW()),
    (gen_random_uuid(), '53159507', 'GTOS NO DEDUCIB SIN SOPORTE LEGAL TARJET', true, NOW(), NOW()),
    (gen_random_uuid(), '53950501', 'DEMANDAS LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '53951001', 'DEMANDAS POR INCUMPLIMIENTO DE CONTRATO', true, NOW(), NOW()),
    (gen_random_uuid(), '53951501', 'INDEMNIZACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53952001', 'MULTAS, SANCIONES Y LITIGIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53952501', 'DONACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53952502', 'DONACIONES DE ACCIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '53959501', 'OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '53959502', 'REINTEGRO GASTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '53959503', 'SIEMBRA CAFÉ GEISHA', true, NOW(), NOW()),
    (gen_random_uuid(), '53959504', 'CASTIGO DE CARTERA', true, NOW(), NOW()),
    (gen_random_uuid(), '54050502', 'IMPUESTO DE RENTA Y COMPLEMENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '59050501', 'GANANCIAS Y PERDIDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '61054501', 'PLATANO', true, NOW(), NOW()),
    (gen_random_uuid(), '61201301', 'CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '61201302', 'DERIVADOS', true, NOW(), NOW()),
    (gen_random_uuid(), '61201303', 'COSTO DE CONTINGENCIA', true, NOW(), NOW()),
    (gen_random_uuid(), '61201304', 'COSTOS DE MUESTRAS DE CALIDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '61209601', 'VARIACION O.P', true, NOW(), NOW()),
    (gen_random_uuid(), '61209602', 'VARIACION CONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '61209603', 'DIFERENCIA DE INVENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '61209604', 'COSTO DE VENTAS INV. DEFECTUOSO', true, NOW(), NOW()),
    (gen_random_uuid(), '61209606', 'PERDIDA POR INVENTARIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '61209607', 'COSTO DE VENTAS INV. B', true, NOW(), NOW()),
    (gen_random_uuid(), '61209608', 'COSTO DE VENTAS INV. SALIDA', true, NOW(), NOW()),
    (gen_random_uuid(), '61209609', 'COSTO DE VENTAS MERCADEO', true, NOW(), NOW()),
    (gen_random_uuid(), '61359501', 'TIENDAS DE CAFE- RESTAURANTE', true, NOW(), NOW()),
    (gen_random_uuid(), '61359502', 'COSTO SOUVENIRS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '61359503', 'COSTO INSUMOS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '61359505', 'OTROS INGRESOS POSICIONAMIENTO DE MARCA', true, NOW(), NOW()),
    (gen_random_uuid(), '61359506', 'ENVASES Y EMPAQUES', true, NOW(), NOW()),
    (gen_random_uuid(), '61359701', 'EXPORTACIONES CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '61359702', 'EXPORTACIONES DE GALLETAS', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '61359703', 'EXPORTACIONES DE AREQUIPE', true, NOW(), NOW()),
    (gen_random_uuid(), '61359704', 'EXPORTACIONES MERMELADA', true, NOW(), NOW()),
    (gen_random_uuid(), '61359705', 'EXPORTACIONES DE MERENGUITOS', true, NOW(), NOW()),
    (gen_random_uuid(), '61359706', 'OTROS INGRESOS POSICION DE MARCA EXPORT.', true, NOW(), NOW()),
    (gen_random_uuid(), '61359707', 'FLETES Y SEGUROS EXPORTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '61359708', 'EXPORTACIONES CAFE VERDE', true, NOW(), NOW()),
    (gen_random_uuid(), '61359901', 'VARIACION CONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '71010101', 'MATERIA PRIMA', true, NOW(), NOW()),
    (gen_random_uuid(), '71010102', 'EMPAQUES Y EMBALAJE', true, NOW(), NOW()),
    (gen_random_uuid(), '71010103', 'MERCANCIA NO FABRICADA POR LA EMPRESA', true, NOW(), NOW()),
    (gen_random_uuid(), '71010104', 'PRODUCTO TERMINADO', true, NOW(), NOW()),
    (gen_random_uuid(), '71019001', 'CONSUMO MP', true, NOW(), NOW()),
    (gen_random_uuid(), '71019090', 'APLICACION DE COSTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '71019091', 'VARIACION EN MERMAS', true, NOW(), NOW()),
    (gen_random_uuid(), '71019092', 'VARIACION BARRIDO DE CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '71019093', 'VARIACION SOBREPESO', true, NOW(), NOW()),
    (gen_random_uuid(), '71019094', 'VARIACION PRODUCTO NO CONFORME', true, NOW(), NOW()),
    (gen_random_uuid(), '71019095', 'VARIACION MATERIAS PRIMAS Y EMPAQUE', true, NOW(), NOW()),
    (gen_random_uuid(), '71019096', 'VARIACION MATERIAS PRIMAS CONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '72010601', 'SUELDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '72011501', 'HORAS EXTRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '72011502', 'RECARGOS DOMINICALES Y FESTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '72012701', 'AUXILIO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '72013001', 'CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '72013301', 'INTERESES SOBRE LAS CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '72013601', 'PRIMA DE SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '72013901', 'VACACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '72014501', 'AUXILIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '72014502', 'AUXILIO CALAMIDAD POR LIBERALIDAD EMPRES', true, NOW(), NOW()),
    (gen_random_uuid(), '72014503', 'AUXILIO PARA COMPRA DE LENTES', true, NOW(), NOW()),
    (gen_random_uuid(), '72014504', 'AUXILIO INCENTIVOS POR ESTUDIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '72014505', 'AUXILIO ARREGLO DE DOTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '72014506', 'AUXILIO PARA TRASLADO DE CIUDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '72014507', 'AUXILIO FUNERARIO', true, NOW(), NOW()),
    (gen_random_uuid(), '72014508', 'AUXILIO ALIMENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '72014801', 'BONIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '72014802', 'BONIFICACIONES POR LIBERALIDAD DE LA EMP', true, NOW(), NOW()),
    (gen_random_uuid(), '72015101', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '72016001', 'INDEMNIZACIONES LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '72016301', 'CAPACITACION AL PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '72016601', 'GASTO DEPORTIVOS Y DE RECREACION', true, NOW(), NOW()),
    (gen_random_uuid(), '72016801', 'APORTES A RIESGOS PREFESIONALES', true, NOW(), NOW()),
    (gen_random_uuid(), '72016901', 'APORTES A EPS', true, NOW(), NOW()),
    (gen_random_uuid(), '72017001', 'APORTES A FONDOS DE PENSIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '72017201', 'APORTES A CAJAS DE COMPENSACION', true, NOW(), NOW()),
    (gen_random_uuid(), '72017501', 'APORTES AL ICBF', true, NOW(), NOW()),
    (gen_random_uuid(), '72017801', 'SENA', true, NOW(), NOW()),
    (gen_random_uuid(), '72018401', 'GASTOS MEDICOS Y DROGAS', true, NOW(), NOW()),
    (gen_random_uuid(), '72990505', 'APLICACION DE COSTOS MOD', true, NOW(), NOW()),
    (gen_random_uuid(), '72990510', 'VARIACION CONTABLE', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '73010601', 'SUELDOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73011501', 'HORAS EXTRAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73011502', 'HORAS EXTRAS MOI', true, NOW(), NOW()),
    (gen_random_uuid(), '73011503', 'RECARGO DOMINICAL Y FESTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73012701', 'AUXILIO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '73013001', 'CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73013301', 'INTERESES SOBRE LAS CESANTIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73013601', 'PRIMA DE SERVICIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73013901', 'VACACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '73014501', 'AUXILIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73014502', 'AUXILIO CALAMIDAD POR LIBERALIDAD EMPRES', true, NOW(), NOW()),
    (gen_random_uuid(), '73014503', 'AUXILIO PARA COMPRA DE LENTES', true, NOW(), NOW()),
    (gen_random_uuid(), '73014504', 'AUXILIO INCENTIVOS POR ESTUDIOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73014505', 'AUXILIO BONO MATERNIDAD / PATERNIDAD', true, NOW(), NOW()),
    (gen_random_uuid(), '73014506', 'AUXILIO FUNERARIO', true, NOW(), NOW()),
    (gen_random_uuid(), '73014507', 'AUXILIO ALIMENTACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73014801', 'BONIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '73014802', 'BONIFICACIONES POR LIBERALIDAD DE LA EMP', true, NOW(), NOW()),
    (gen_random_uuid(), '73015101', 'DOTACION Y SUMINISTRO A TRABAJADORES', true, NOW(), NOW()),
    (gen_random_uuid(), '73016001', 'INDEMNIZACIONES LABORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '73016301', 'CAPACITACION AL PERSONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '73016601', 'GASTO DEPORTIVOS Y DE RECREACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73016801', 'APORTES A RIESGOS PREFESIONALES', true, NOW(), NOW()),
    (gen_random_uuid(), '73016901', 'APORTES A EPS', true, NOW(), NOW()),
    (gen_random_uuid(), '73017001', 'APORTES A FONDOS DE PENSIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '73017201', 'APORTES A CAJAS DE COMPENSACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73017501', 'APORTES AL ICBF', true, NOW(), NOW()),
    (gen_random_uuid(), '73017801', 'SENA', true, NOW(), NOW()),
    (gen_random_uuid(), '73018401', 'GASTOS MEDICOS Y DROGAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73101501', 'HONORARIOS AUDITORIA EXTERNA', true, NOW(), NOW()),
    (gen_random_uuid(), '73103501', 'ASESORIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '73103502', 'HONORARIOS PRESTADOS EN EL EXTERIOR', true, NOW(), NOW()),
    (gen_random_uuid(), '73202501', 'EQUIPO DE COMUNICACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73209501', 'ARRENDAMIENTO MUEBLES OTROS', true, NOW(), NOW()),
    (gen_random_uuid(), '73251001', 'AFILIACIONES Y SOSTENIMIENTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73300501', 'MANEJO', true, NOW(), NOW()),
    (gen_random_uuid(), '73301001', 'CUMPLIMIENTO', true, NOW(), NOW()),
    (gen_random_uuid(), '73301601', 'SEGURO DE ACTIVOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73302501', 'INCENDIO', true, NOW(), NOW()),
    (gen_random_uuid(), '73303501', 'SUSTRACCION Y HURTO', true, NOW(), NOW()),
    (gen_random_uuid(), '73308501', 'SEGURO TRANSPORTE DE EXPORTACIÓN', true, NOW(), NOW()),
    (gen_random_uuid(), '73350501', 'ASEO Y VIGILANCIA', true, NOW(), NOW()),
    (gen_random_uuid(), '73351001', 'TEMPORALES', true, NOW(), NOW()),
    (gen_random_uuid(), '73351501', 'ASISTENCIA TECNICA', true, NOW(), NOW()),
    (gen_random_uuid(), '73352001', 'PROCESAMIENTO ELECTRONICPO DE DATOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73352501', 'ACUEDUCTO Y ALCANTARILLADO', true, NOW(), NOW()),
    (gen_random_uuid(), '73353001', 'ENERGIA', true, NOW(), NOW()),
    (gen_random_uuid(), '73353002', 'ENERGIA SOLAR', true, NOW(), NOW()),
    (gen_random_uuid(), '73353501', 'TELEFONO', true, NOW(), NOW()),
    (gen_random_uuid(), '73354001', 'CORREO, PORTES Y TELEGRAMAS', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '73355001', 'TRANSPORTES, FLETES Y ACARREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73355501', 'GAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73356001', 'PUBLICIDAD, PROPAGANDA Y PROMOCION', true, NOW(), NOW()),
    (gen_random_uuid(), '73359001', 'INTERNET', true, NOW(), NOW()),
    (gen_random_uuid(), '73359501', 'SERVICIO DE MEZCLA', true, NOW(), NOW()),
    (gen_random_uuid(), '73359502', 'OTROS * SERVICIOS VIRTUALES', true, NOW(), NOW()),
    (gen_random_uuid(), '73401501', 'TRAMITES Y LICENCIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73402001', 'ADUANEROS', true, NOW(), NOW()),
    (gen_random_uuid(), '73451501', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '73451502', 'REPUESTOS MAQ PLANTA', true, NOW(), NOW()),
    (gen_random_uuid(), '73451503', 'REPUESTOS MAQ TIENDAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73452501', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73500501', 'INSTALACIONES ELECTRICAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73501501', 'REPARACIONES LOCATIVAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73550501', 'ALOJAMIENTO Y MANUTENCION', true, NOW(), NOW()),
    (gen_random_uuid(), '73551501', 'PASAJES AEREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73551502', 'PASAJES TERRESTRES', true, NOW(), NOW()),
    (gen_random_uuid(), '73600501', 'CONSTRUCCIONES Y EDIFICACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '73601001', 'MAQUINARIA Y EQUIPO', true, NOW(), NOW()),
    (gen_random_uuid(), '73601501', 'EQUIPO DE OFICINA', true, NOW(), NOW()),
    (gen_random_uuid(), '73602001', 'EQUIPO DE COMPUTACION Y COMUNICACION', true, NOW(), NOW()),
    (gen_random_uuid(), '73603501', 'FLOTA Y EQUIPO DE TRANSPORTE', true, NOW(), NOW()),
    (gen_random_uuid(), '73650101', 'ANALISIS Y MONITOREOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73650102', 'SERVICIO DE FLETE', true, NOW(), NOW()),
    (gen_random_uuid(), '73650103', 'AMORTIZACION REPUESTOS', true, NOW(), NOW()),
    (gen_random_uuid(), '73952501', 'ELEMENTOS DE ASEO Y CAFETERIA', true, NOW(), NOW()),
    (gen_random_uuid(), '73953001', 'UTILES, PAPELERIA Y FOTOCOPIAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73953002', 'IMPRESOS, LITOGRAFIA Y TIPOGRAFIA', true, NOW(), NOW()),
    (gen_random_uuid(), '73953501', 'COMBUSTIBLES Y LUBRICANTES', true, NOW(), NOW()),
    (gen_random_uuid(), '73954001', 'ENVASES, EMPAQUES Y CINTAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73954501', 'TAXIS Y BUSES', true, NOW(), NOW()),
    (gen_random_uuid(), '73956001', 'CASINO Y RESTAURANTE', true, NOW(), NOW()),
    (gen_random_uuid(), '73956501', 'PARQUEADERO', true, NOW(), NOW()),
    (gen_random_uuid(), '73959501', 'ANALISIS DE LABORATORIO', true, NOW(), NOW()),
    (gen_random_uuid(), '73959502', 'CARGUE - DESCARGUE Y TRILLA DE CAFE', true, NOW(), NOW()),
    (gen_random_uuid(), '73959503', 'AVERIAS CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '73959504', 'COMPRA EQU.MENORES,MUEBLES,ACCES Y UTENS', true, NOW(), NOW()),
    (gen_random_uuid(), '73959505', 'OBSEQUIOS Y DEGUSTACIONES', true, NOW(), NOW()),
    (gen_random_uuid(), '73959506', 'SERVICIO DE TRILLA', true, NOW(), NOW()),
    (gen_random_uuid(), '73959507', 'ELEMENTOS SALUD OCUPACIONAL', true, NOW(), NOW()),
    (gen_random_uuid(), '73959508', 'CIF COMPRA CAFE PERGAMINO', true, NOW(), NOW()),
    (gen_random_uuid(), '73959509', 'INSUMOS PARA PRUEBAS', true, NOW(), NOW()),
    (gen_random_uuid(), '73959510', 'PEAJES', true, NOW(), NOW()),
    (gen_random_uuid(), '73990505', 'APLICACION DE COSTOS CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '73990506', 'VARIACION COSTO ESTANDAR MP', true, NOW(), NOW()),
    (gen_random_uuid(), '73990507', 'VARIACION COSTO ESTANDAR MOD', true, NOW(), NOW()),
    (gen_random_uuid(), '73990508', 'VARIACION COSTO ESTANDAR CIF', true, NOW(), NOW()),
    (gen_random_uuid(), '73990510', 'VARIACION CONTABLE', true, NOW(), NOW()),
    (gen_random_uuid(), '73990511', 'IVA MAYOR VALOR DEL COSTO', true, NOW(), NOW()),
    (gen_random_uuid(), '81152001', 'EN CONSIGNACION', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO cuentas_auxiliares (id, codigo, descripcion, activa, created_at, updated_at)
VALUES
    (gen_random_uuid(), '86950501', 'CHEQUES POSTFECHADOS', true, NOW(), NOW())
ON CONFLICT (codigo) DO NOTHING;

