"""Initial migration: areas, users, estados, facturas, files

Revision ID: 54350e564c80
Revises: 
Create Date: 2025-12-22 15:13:00.485965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54350e564c80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_nombre'), 'areas', ['nombre'], unique=True)
    op.create_table('estados',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_code'), 'estados', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'area_manager', 'user')", name='check_user_role'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proveedor', sa.Text(), nullable=False),
    sa.Column('numero_factura', sa.Text(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado_id', sa.SmallInteger(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total > 0', name='check_factura_total_positive'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor', 'numero_factura', name='uq_factura_proveedor_numero')
    )
    op.create_index(op.f('ix_facturas_area_id'), 'facturas', ['area_id'], unique=False)
    op.create_index(op.f('ix_facturas_assigned_to_user_id'), 'facturas', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_facturas_estado_area', 'facturas', ['estado_id', 'area_id'], unique=False)
    op.create_index(op.f('ix_facturas_estado_id'), 'facturas', ['estado_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("storage_provider IN ('local', 's3', 'drive')", name='check_file_storage_provider'),
    sa.CheckConstraint('size_bytes > 0', name='check_file_size_positive'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_factura_id'), 'files', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_factura_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_facturas_estado_id'), table_name='facturas')
    op.drop_index('ix_facturas_estado_area', table_name='facturas')
    op.drop_index(op.f('ix_facturas_assigned_to_user_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_area_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_estados_code'), table_name='estados')
    op.drop_table('estados')
    op.drop_index(op.f('ix_areas_nombre'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
